<?php
/*
 * Copyright 2004 Matt Brubeck
 * This file is licensed under a Creative Commons license:
 * http://creativecommons.org/licenses/by/2.0/
 */
class NewsItem {
  var $id;
  var $date;
  var $title;
  var $body;

  // Constructor.
  function NewsItem($date, $title, $body) {
    $this->date = $date;
    $this->title = $title;
    $this->body = $body;
  }

  // Returns the date, in the preferred format for the current locale.
  function dateStr() {
    // i18n-hint: Controls how dates are formatted.
    // See http://www.php.net/manual/function.strftime.php for details.
    return locale_to_unicode(strftime(_("%B %d, %Y"), $this->date));
  }
}

$news_items = array();
function add_news_item($dateStr, $id, $title, $body) {
  global $news_items;
  $date = strtotime($dateStr);
  $key = strftime("%Y-%m-%d", $date)."/".$id;
  $news_items[$key] = new NewsItem($date, $title, $body);
}
function most_recent_news_item() {
}

add_news_item(
  "Dec 31, 2009",
	"oreka-1.2",
  _("Oreka 1.2 is released"),
  _('<p>Includes Windows and Linux installers.</p><p><font color="red"> WARNING: if you are upgrading OrkWeb/OrkTrack from 0.5-311, the database schema has changed.  Please use the database script file: <a href="http://sourceforge.net/projects/oreka/files/oreka/oreka-1.2/orkweb/updateOrekaDB_to_v1.zip/download">updateOrekaDB_to_v1.zip</a>.</font><font>  It includes a README.txt file and a .sql script file with details in the header.</font></p>')
);

add_news_item(
  "Sept 2, 2009",
	"asterisk-xorcom",
  _("Asterisk interception via Xorcom Asterisk patch"),
  _('<p>Added support for recording of Asterisk voice calls (TDM and IP) using Xorcoms Asterisk patch. See <a href=http://www.xorcom.com/news-archive/call-recording-pr.html>here</a>.</p>')
);

add_news_item(
  "July 31, 2009",
	"skinny-cucm7",
  _("Skinny CUCM 7 Support"),
  _('<p>Added support for the latest Cisco Unified Communications Manager (7.1)</p>')
);

add_news_item(
  "Jan 15, 2009",
	"g722-support",
  _("G.722 Support"),
  _('<p>Added support for G.722 speech codec.</p>')
);

add_news_item(
  "August 05, 2008",
	"inin-mode",
  _("Interactive intelligence support"),
  _('<p>Suppor for Interactive intelligence telephony platform has been enhanced.</p>')
);

add_news_item(
  "April 08, 2008",
	"rtp-tap",
  _("Sangoma TDM boards RTP tap"),
  _('<p>Oreka is now able to intercept and record RTP traffic generated by Sangoma TDM boards via the wanpipe driver. This allows for passive recording of TDM lines even when calls have no VoIP leg. For more info see <a href=http://wiki.sangoma.com/wanpipe-voice-rtp-tap>Wanpipe voice RTP tap</a>.</p>')
);

add_news_item(
  "February 27, 2008",
	"stereo-recording",
  _("Stereo recording"),
  _('<p>It is now possible to record audio files with near end and far end separated in two stereo channels which can be useful for analytics. This is currently limited to the G.711 storage format.</p>')
);

add_news_item(
  "September 27, 2007",
	"oob-dtmf-extraction",
  _("DTMF extraction"),
  _('<p>RTP out-of-band DTMF digits can now be extracted and reported in tape messages as tags.</p>')
);

add_news_item(
  "September 06, 2007",
	"audio-file-naming",
  _("Audio file naming now configurable"),
  _('<p>File names of generated audio files can now be built from various parameters such as phone numbers, IP addresses, etc.</p>')
);

add_news_item(
  "August 30, 2007",
	"wifi-support",
  _("Added Wifi support"),
  _('<p>Oreka can now intercept and record Wifi 802.11 VoIP traffic.</p>')
);

add_news_item(
  "April 13, 2007",
	"sip-extraction",
  _("Added SIP extraction feature"),
  _('<p>It is now possible to extract aritrary fields from SIP headers which are reported in tape messages as tags.</p>')
);

add_news_item(
  "February 06, 2007",
	"iax2-support",
  _("IAX2 native Asterisk signalling is now supported"),
  _('<p>Support for IAX2 will allow better interoperability with Asterisk based platforms.</p>')
);

add_news_item(
  "January 26, 2007",
	"ilbc-support",
  _("iLBC RTP payload type is now supported"),
  _('<p>Support for iLBC wire format has been added in subversion by Gerald Begumisa. Nice job Gerald! The upcoming release will include this feature.</p>')
);

add_news_item(
  "November 10, 2006",
	"gsm-support",
  _("GSM RTP payload type is now supported"),
  _('<p>Support for GSM6.10 wire format has been added in subversion (GSM as a storage format has been default since the first release of Oreka). Thanks to <a href="http://kbs.cs.tu-berlin.de/~jutta/toast.html">Jutta Degener and Carsten Bormann</a> from Technische Universitaet Berlin for making this codec available. Stay tuned for an official release of the latest trunk (0.6 branch).</p>')
);

add_news_item(
  "July 27, 2006",
	"oreka-0.5-313-release",
  _("Oreka 0.5-313 released"),
  _('<p>We are proud to annouce the latest version of Oreka. This release adds support for the new Cisco CallManager 5, big robustness improvements and better Skinny and SIP support. For more info, please refer to the <a href="download/release-notes">release notes</a>.</p>')
);



add_news_item(
  "June 08, 2006",
	"svn-migration",
  _("Migration to Subversion"),
  _('<p>We have moved the code to Subversion! Point your browsers <a href="http://svn.sourceforge.net/viewcvs.cgi/oreka/">here</a> for Web access to the repository. If you check out, be careful to only check out the trunk: <a href="https://svn.sourceforge.net/svnroot/oreka/trunk/">https://svn.sourceforge.net/svnroot/oreka/trunk/</a> or a branch. CVS access is still available for now.</p>')
);


add_news_item(
  "March 23, 2006",
	"user-manual",
  _("New User Manual"),
  _('<p>A <a href="http://oreka.sourceforge.net/oreka-user-manual.html">new user manual</a> has been created, completing  the existing developer documentation.</p>')
);

add_news_item(
  "February 16, 2006",
	"0.5-release",
  _("Oreka 0.5 Released"),
  _('<p>This release corrects a critical bug where Oreka could crash given a cerain RTP sequence. Also, SIP detection has been improved on some platforms (Siemens).</p>')
);

add_news_item(
  "February 12, 2006",
	"0.4-release",
  _("Oreka 0.4 Released"),
  _('<p>This release corrects a few SIP and Cisco Skinny related issues. VoIP recording is now more robust. Additionally, it is now possible to run a pcap trace file against OrkAudio. Binary RPMs are now available for download (Redhat/CentOS).</p>')
);



add_news_item(
  "February 03, 2006",
	"Orkaudio compiles and runs on FreeBSD",
  _("Orkaudio compiles and runs on FreeBSD"),
  _('<p>Please see the developers mailing list for details.</p>')
);



add_news_item(
  "January 25, 2006",
	"Windows installer fix",
  _("Windows installer fix"),
  _('<p>A flaw was fixed in the OrkAudio windows installer where Winpcap could go uninstalled, preventing OrkAudio from capturing VoIP traffic. Grab the latest version on the <a href="download">download</a> section (file name and version unchanged, still 0.3)</p>')
);


add_news_item(
  "December 08, 2005",
	"Web UI available as binary",
  _("Web UI available as binary"),
  _('<p>The web interface (OrkWeb) is now available as a precompiled Java war file. See the <a href="download">download</a> section for more info</p>')
);

add_news_item(
  "November 24, 2005",
	"0.3-release",
  _("Oreka 0.3 Released"),
  _('<p>A windows installer and a debian/ubuntu package are now available, making it easier for users to install the orkaudio recorder. Orkaudio can now run as a daemon under Linux.</p>')
);



add_news_item(
  "November 02, 2005",
	"0.2-release",
  _("Oreka 0.2 Released"),
  _('<p>OrkAudio now supports Cisco Skinny (aka SCCP) recording. This allows Cisco Call Manager sessions to be captured. Also, Support for raw RTP recording has been added. OrkAudio defaults to this for RTP based protocols other than SIP and Skinny.</p>')
);


add_news_item(
  "October 26, 2005",
	"0.1-release",
  _("Oreka 0.1 Released"),
  _('<p>This is the first public release of oreka. Please check it out and let us know issues you are encountering on oreka-devel and oreka-user mailing lists.</p>')
);
?>
